//! `Usage` — unified token usage statistics for all supported protocols.

use serde::{Deserialize, Serialize};

/// Server-side tool call usage counts.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ServerToolUsage {
    pub web_search_requests: u32,
    pub web_fetch_requests: u32,
}

/// Token usage statistics for a request/response pair.
///
/// Field naming follows IR conventions:
/// - `prompt_tokens`      — input tokens (prompt + cached context)
/// - `completion_tokens`  — output tokens generated by the model
/// - `total_tokens`       — prompt + completion (may be 0 if not supplied by provider)
/// - `cache_read_tokens`  — tokens served from the prompt cache (Anthropic / compatible)
/// - `cache_creation_tokens` — tokens written to the prompt cache
/// - `server_tool_use`    — server-side tool call counts (web search, web fetch)
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Usage {
    pub prompt_tokens: u32,
    pub completion_tokens: u32,
    pub total_tokens: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_read_tokens: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_creation_tokens: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub server_tool_use: Option<ServerToolUsage>,
}
